#!/bin/bash

echo "*******************************************************************************************************************************************"
echo "*Now,you should be able update your package list,upgrade,dist-upgrade and clean up your system automatically with the command 'newVersion'*"
echo "*******************************************************************************************************************************************"
